--- 
abstract: ~
author: 
  - Maxim Grigoriev <maxim |AT| fnal.gov>, 2007-2008, Fermilab
distribution_type: module
generated_by: Module::Install version 0.68
license: Fermitools
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Config-Interactive
no_index: 
  directory: 
    - t
    - inc
    - t
requires: 
  Data::Dumper: 0
  Test::More: 0
  XML::Parser: 0
  XML::Simple: 0
  fields: 0
  perl: 5.6.1
version: 0.04
